version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: api-doc-pg
    restart: always
    environment:
      POSTGRES_DB: apisolid
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
